update

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -45,11 +45,16 @@ jobs:
         username: ${{ secrets.SERVER_USERNAME }}
         key: ${{ secrets.SERVER_SSH_KEY }}
         script: |
-          echo "Current PATH: $PATH"
-          echo "npm location: $(which npm || echo 'npm not found')"
-          echo "npx location: $(which npx || echo 'npx not found')"
-          echo "pm2 location: $(which pm2 || echo 'pm2 not found')"
-          echo "HOME: $HOME"
-          echo "Current working directory: $(pwd)"
-          echo "Current user: $(whoami)"
+          echo "Creating info.txt in the root of the VPS"
+          cat > /info.txt <<- EOM
+          Current PATH: $PATH
+          npm location: $(which npm || echo 'npm not found')
+          npx location: $(which npx || echo 'npx not found')
+          pm2 location: $(which pm2 || echo 'pm2 not found')
+          HOME: $HOME
+          Current working directory: $(pwd)
+          Current user: $(whoami)
+          EOM
+          echo "info.txt created successfully"
+
 
